services:
  - type: web
    name: sonar-1-iop9
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sonar-backend-2.onrender.com/api
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
